language: r
cache: packages

matrix:
  include:
  - r: devel
  - r: release

sudo: false

addons:
  apt:
    packages:
      - qpdf
      - xvfb
      
services:
  - xvfb

r_binary_packages:
  - vegan3d
  - rgl
  - vegan
  - analogue

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: " --compact-vignettes=gs+qpdf"

notifications:
  email:
    on_success: change
    on_failure: always
